<?php // clear;php5 -f WsWds/index.php
// WsWdsScript

$workingFolder = dirname(__FILE__).DIRECTORY_SEPARATOR;

require_once($GLOBALS['workingFolder'].'/resources/php/configManager.phpc');
$WsWdsConfig = configManager::getConfig('global');

// if (is_file('./WsWds.conf')) {
//     $WsWdsConfig = eval('return '.file_get_contents('./WsWds.conf').';');
// } else { // do NOT edit this file
//     $WsWdsConfig = eval('return '.file_get_contents('./WsWds.default.conf').';');
// }

// include_once($_WsWdsFOLDER .'StationScript/index.php');
include_once($GLOBALS['workingFolder'].'admin/index.php');

?>
