<?php // clear;php5 -f WsWds/index.php
// WsWdsScript

$_WsWdsFOLDER = dirname(__FILE__).DIRECTORY_SEPARATOR;

if (is_file('./WsWds.conf')) {
    $WsWdsConfig = eval('return '.file_get_contents('./WsWds.conf').';');
} else { // do NOT edit this file
    $WsWdsConfig = eval('return '.file_get_contents('./WsWds.default.conf').';');
}

// include_once($_WsWdsFOLDER .'StationScript/index.php');
include_once($_WsWdsFOLDER .'admin/index.php');

?>
