<?php
require_once 'Hilow.phpc';

// +++++++++++++++++++++++++++++++++++++++++++++++++++++++

// +++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++ VAR DEFINITION ++++++++++++++++++++++
$measures = array(
  'BarometerSection' => new BarometerSection(0, 16),
  'CRC' => new CRC(436, 2),
  'DailyHighBarometer' => new DailyHighBarometer(2, 2),
  'DailyHiWindSpeed' => new DailyHiWindSpeed(16, 1),
  'DailyLowBarometer' => new DailyLowBarometer(0, 2),
  'DayHiDewPoint' => new DayHiDewPoint(65, 2),
  'DayHighHeat' => new DayHighHeat(87, 2),
  'DayHighRainRate' => new DayHighRainRate(116, 2),
  'DayHighSolarRad' => new DayHighSolarRad(103, 2),
  'DayHighTHSW' => new DayHighTHSW(95, 2),
  'DayHighUV' => new DayHighUV(111, 1),
  'DayHiHumidity' => new DayHiHumidity(284, 8),
  'DayHiInHum' => new DayHiInHum(37, 1),
  'DayHiInsideTemp' => new DayHiInsideTemp(21, 2),
  'DayHiLeafWetness' => new DayHiLeafWetness(396, 4),
  'DayHiOutTemp' => new DayHiOutTemp(49, 2),
  'DayHiSoilMoisture' => new DayHiSoilMoisture(356, 4),
  'DayHiTemperature' => new DayHiTemperature(141, 15),
  'DayLowDewPoint' => new DayLowDewPoint(63, 2),
  'DayLowHumidity' => new DayLowHumidity(276, 8),
  'DayLowInHum' => new DayLowInHum(38, 1),
  'DayLowInsideTemp' => new DayLowInsideTemp(23, 2),
  'DayLowLeafWetness' => new DayLowLeafWetness(408, 4),
  'DayLowOutTemp' => new DayLowOutTemp(47, 2),
  'DayLowSoilMoisture' => new DayLowSoilMoisture(368, 4),
  'DayLowTemperature' => new DayLowTemperature(126, 15),
  'DayLowWindChill' => new DayLowWindChill(79, 2),
  'DewPointSection' => new DewPointSection(63, 16),
  'Extra_Leaf_SoilTemps' => new Extra_Leaf_SoilTemps(126, 150),
  'HeatIndexSection' => new HeatIndexSection(87, 8),
  'HourHighRainRate' => new HourHighRainRate(120, 2),
  'InsideHumiditySection' => new InsideHumiditySection(37, 10),
  'InsideTempSection' => new InsideTempSection(21, 16),
  'LeafWetnessSection' => new LeafWetnessSection(396, 40),
  'MonthHiDewPoint' => new MonthHiDewPoint(71, 2),
  'MonthHighBar' => new MonthHighBar(6, 2),
  'MonthHighHeat' => new MonthHighHeat(91, 2),
  'MonthHighRainRate' => new MonthHighRainRate(122, 2),
  'MonthHighSolarRad' => new MonthHighSolarRad(107, 2),
  'MonthHighTHSW' => new MonthHighTHSW(99, 2),
  'MonthHighUV' => new MonthHighUV(114, 1),
  'MonthHiHumidity' => new MonthHiHumidity(324, 8),
  'MonthHiInHum' => new MonthHiInHum(43, 1),
  'MonthHiInTemp' => new MonthHiInTemp(31, 2),
  'MonthHiLeafWetness' => new MonthHiLeafWetness(424, 4),
  'MonthHiOutTemp' => new MonthHiOutTemp(55, 2),
  'MonthHiSoilMoisture' => new MonthHiSoilMoisture(384, 4),
  'MonthHiTemperature' => new MonthHiTemperature(216, 15),
  'MonthHiWindSpeed' => new MonthHiWindSpeed(19, 1),
  'MonthLowBar' => new MonthLowBar(4, 2),
  'MonthLowDewPoint' => new MonthLowDewPoint(73, 2),
  'MonthLowHumidity' => new MonthLowHumidity(332, 8),
  'MonthLowInHum' => new MonthLowInHum(44, 1),
  'MonthLowInTemp' => new MonthLowInTemp(29, 2),
  'MonthLowLeafWetness' => new MonthLowLeafWetness(420, 4),
  'MonthLowOutTemp' => new MonthLowOutTemp(57, 2),
  'MonthLowSoilMoisture' => new MonthLowSoilMoisture(380, 4),
  'MonthLowTemperature' => new MonthLowTemperature(231, 15),
  'MonthLowWindChill' => new MonthLowWindChill(83, 2),
  'Outside_ExtraHums' => new Outside_ExtraHums(276, 80),
  'OutsideTempSection' => new OutsideTempSection(47, 16),
  'RainRateSection' => new RainRateSection(116, 10),
  'SoilMoistureSection' => new SoilMoistureSection(356, 40),
  'SolarRadiationSection' => new SolarRadiationSection(103, 8),
  'THSWIndexSection' => new THSWIndexSection(95, 8),
  'TimeDayHiDewPoint' => new TimeDayHiDewPoint(69, 2),
  'TimeDayHiHumidity' => new TimeDayHiHumidity(308, 16),
  'TimeDayHiInHum' => new TimeDayHiInHum(39, 2),
  'TimeDayHiInTemp' => new TimeDayHiInTemp(25, 2),
  'TimeDayHiLeafWetness' => new TimeDayHiLeafWetness(400, 8),
  'TimeDayHiOutTemp' => new TimeDayHiOutTemp(53, 2),
  'TimeDayHiSoilMoisture' => new TimeDayHiSoilMoisture(360, 8),
  'TimeDayHiTemperature' => new TimeDayHiTemperature(186, 30),
  'TimeDayLowChill' => new TimeDayLowChill(81, 2),
  'TimeDayLowDewPoint' => new TimeDayLowDewPoint(67, 2),
  'TimeDayLowHumidity' => new TimeDayLowHumidity(292, 16),
  'TimeDayLowInHum' => new TimeDayLowInHum(41, 2),
  'TimeDayLowInTemp' => new TimeDayLowInTemp(27, 2),
  'TimeDayLowLeafWetness' => new TimeDayLowLeafWetness(412, 8),
  'TimeDayLowOutTemp' => new TimeDayLowOutTemp(51, 2),
  'TimeDayLowSoilMoisture' => new TimeDayLowSoilMoisture(372, 8),
  'TimeDayLowTemperature' => new TimeDayLowTemperature(156, 30),
  'TimeofDayHighBar' => new TimeofDayHighBar(14, 2),
  'TimeofDayHighHeat' => new TimeofDayHighHeat(89, 2),
  'TimeofDayHighRainRate' => new TimeofDayHighRainRate(118, 2),
  'TimeofDayHighSolar' => new TimeofDayHighSolar(105, 2),
  'TimeofDayHighTHSW' => new TimeofDayHighTHSW(97, 2),
  'TimeofDayHighUV' => new TimeofDayHighUV(112, 2),
  'TimeofDayLowBar' => new TimeofDayLowBar(12, 2),
  'TimeofHiSpeed' => new TimeofHiSpeed(17, 2),
  'UVSection' => new UVSection(111, 5),
  'WindChillSection' => new WindChillSection(79, 8),
  'WindSpeedSection' => new WindSpeedSection(16, 5),
  'YearHiDewPoint' => new YearHiDewPoint(75, 2),
  'YearHighBarometer' => new YearHighBarometer(10, 2),
  'YearHighHeat' => new YearHighHeat(93, 2),
  'YearHighRainRate' => new YearHighRainRate(124, 2),
  'YearHighSolarRad' => new YearHighSolarRad(109, 2),
  'YearHighTHSW' => new YearHighTHSW(101, 2),
  'YearHighUV' => new YearHighUV(115, 1),
  'YearHiHumidity' => new YearHiHumidity(340, 8),
  'YearHiInHum' => new YearHiInHum(45, 1),
  'YearHiInTemp' => new YearHiInTemp(35, 2),
  'YearHiLeafWetness' => new YearHiLeafWetness(432, 4),
  'YearHiOutTemp' => new YearHiOutTemp(59, 2),
  'YearHiSoilMoisture' => new YearHiSoilMoisture(392, 4),
  'YearHiTemperature' => new YearHiTemperature(246, 15),
  'YearHiWindSpeed' => new YearHiWindSpeed(20, 1),
  'YearLowBarometer' => new YearLowBarometer(8, 2),
  'YearLowDewPoint' => new YearLowDewPoint(77, 2),
  'YearLowHumidity' => new YearLowHumidity(348, 8),
  'YearLowInHum' => new YearLowInHum(46, 1),
  'YearLowInTemp' => new YearLowInTemp(33, 2),
  'YearLowLeafWetness' => new YearLowLeafWetness(428, 4),
  'YearLowOutTemp' => new YearLowOutTemp(61, 2),
  'YearLowSoilMoisture' => new YearLowSoilMoisture(388, 4),
  'YearLowTemperature' => new YearLowTemperature(261, 15),
  'YearLowWindChill' => new YearLowWindChill(85, 2),
);

// +++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++ VAR DEFINITION ++++++++++++++++++++++
$rawDataFilePath = dirname(__FILE__).'/VP2-data.brut';
$rawDataString = file_get_contents($rawDataFilePath);

foreach ($measures as $measureKey => $measureObject)
{
  printf(
  "%s\t(%s), \tfrom %s+%d = raw[%s] hex<>dec[%s|%s]]\n",
  $measureKey,
  $measureObject->getFieldDescription(),
  $measureObject->getFieldOffset(),
  $measureObject->getFieldSize(),
  $measureObject->extractRawField($rawDataString),
  Fields::hexToDec($measureObject->extractRawField($rawDataString)), // get correct value
  bin2hex($measureObject->extractRawField($rawDataString))
  );
  }
?>