<?php
class configManager
{
    private $_configFile = null;

//     static function setConfig($value) {
//         $this->_config = $value;
//     }
    static function readConfig($requestedConfig) {
	$workingFolder = dirname(__FILE__).DIRECTORY_SEPARATOR;
        switch ($requestedConfig) {
            case 'station':
                $config = self::fetchConfig($workingFolder.'stations.php');
                break;
            case 'global':
                $config = self::fetchConfig($workingFolder.'WsWds.php');
                break;
            default:
                $config = null;
        }

        return $config;
    }
 // @description: config
   static function writeConfig($requestedConfig, $arrayData) {
	$workingFolder = dirname(__FILE__).DIRECTORY_SEPARATOR;
	$str = "<?php\n\$conf = ".var_export($arrayData, true).";\n?>";
	switch ($requestedConfig) {
		case 'station':
			return file_put_contents($workingFolder.'stations.php', $str);
			break;
		case 'global':
			return file_put_contents($workingFolder.'WsWds.php', $str);
			break;
	}
	return false;
    }

    /*
     * @description: return the content of the config file if its present and readable, null otherwise
     * @return: array or null
     */
    static function fetchConfig($filePath) { //
        if (self::_is_avaible($filePath)) {
            include ($filePath);
        } else { // do NOT edit this file
                $conf = null;
        }
        return $conf;
    }

    /*
     * @description: check if the file is readable, display an error otherwise
     * @return: boolean
     */
    static function _is_avaible($filename) { //
        if (!is_file($filename)) {
            echo _(sprintf('The file <i>%s</i> is <strong>not a file</strong>', $filename));
            return FALSE;
        } 
        if (!is_readable($filename)) {
            echo _(sprintf('The file <i>%s</i> is <strong>not</strong> readable', $filename));
            return FALSE;
        } 
        if (!is_writable($filename)) {
            echo _(sprintf('The file <i>%s</i> is <strong>not</strong> writable', $filename));
            return FALSE;
        }
        return true;
    }


    /*
     * @description: wswds
     * @return: global configuration file
     */
    static function fetchGlobalConfig() { //
        if (is_file( $GLOBALS['workingFolder'].'./WsWds.conf')) {
            $globalConfig = eval('return '.file_get_contents($GLOBALS['workingFolder'].'./WsWds.conf').';');
        } else { // do NOT edit this file
            $globalConfig = eval('return '.file_get_contents($GLOBALS['workingFolder'].'./WsWds.default.conf').';');
        }
        return $globalConfig;
    }


    function __construct($requestedConfig) {
    }

}

?>
